-- ACS Experiments
ALTER TABLE acs_income ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE acs_income ALTER column COW SET STATISTICS 10000;
ALTER TABLE acs_income ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE acs_income ALTER column MAR SET STATISTICS 10000;
ANALYZE acs_income;

ALTER TABLE a_p1 ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE a_p1 ALTER column COW SET STATISTICS 10000;
ALTER TABLE a_p1 ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE a_p1 ALTER column MAR SET STATISTICS 10000;
ALTER TABLE a_p1 ALTER column AGEP_stat SET STATISTICS 10000;
ANALYZE a_p1;

ALTER TABLE a_p2 ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE a_p2 ALTER column COW SET STATISTICS 10000;
ALTER TABLE a_p2 ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE a_p2 ALTER column MAR SET STATISTICS 10000;
ALTER TABLE a_p2 ALTER column SCHL_stat SET STATISTICS 10000;
ANALYZE a_p2;

ALTER TABLE a_p3 ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE a_p3 ALTER column COW SET STATISTICS 10000;
ALTER TABLE a_p3 ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE a_p3 ALTER column MAR SET STATISTICS 10000;
ALTER TABLE a_p3 ALTER column AGEP_stat SET STATISTICS 10000;
ANALYZE a_p3;

ALTER TABLE a_p4 ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE a_p4 ALTER column COW SET STATISTICS 10000;
ALTER TABLE a_p4 ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE a_p4 ALTER column MAR SET STATISTICS 10000;
ALTER TABLE a_p4 ALTER column SCHL_stat SET STATISTICS 10000;
ANALYZE a_p4;

ALTER TABLE a_p5 ALTER column AGEP SET STATISTICS 10000;
ALTER TABLE a_p5 ALTER column COW SET STATISTICS 10000;
ALTER TABLE a_p5 ALTER column SCHL SET STATISTICS 10000;
ALTER TABLE a_p5 ALTER column MAR SET STATISTICS 10000;
ALTER TABLE a_p5 ALTER column AGEP_stat SET STATISTICS 10000;
ALTER TABLE a_p5 ALTER column SCHL_stat SET STATISTICS 10000;
ANALYZE a_p5;
